// utils/iconMapping.js
import {
  MessagesSquare,
  CalendarDays,
  UserPlus,
  Handshake,
  Rocket,
  MapPin,
  Building,
  Users,
  Heart,
  Star,
  Trophy,
  Camera,
  Music,
  Coffee,
  ShoppingBag,
  Briefcase,
  GraduationCap,
  MousePointerClick,
  MoreHorizontal,
  AlertTriangle,
  // Newly added below
  Building2,
  UserRound,
  Car,
  Cloud,
  PartyPopper,
  Swords,
  Megaphone,
  AlertCircle,
  Film,
  Laptop,
  FlaskConical,
  Leaf,
  Train,
  Globe,
  BadgeDollarSign,
  Ambulance,
  Clapperboard,
  Shield,
  Shirt,
  BellRing,
  Flag,
  PawPrint,
  Loader2,
  Newspaper,
  TrendingUp,
  HandHeart,
  Sparkles,
  Info,
  RotateCw,
  DollarSign,
  AlertOctagon,
  Speaker,
  Target,
  Vote,
  UsersRound,
  Code2,
  LogIn,
  Smartphone,
  Sofa,
  Home,
  Package,
  Percent,
  Gift,
  SpeakerIcon,
  Cross,
  ShieldAlert,
  Zap,
  Droplet,
  Refrigerator,
  MessageCircleQuestion,
  Wrench,
  Snowflake,
  Video,
  ArrowUpDown,
  Dumbbell,
  Wifi,
  Trash2,
} from "lucide-react";
import { FaHandcuffs, FaToolbox } from "react-icons/fa6";
import { GiCrossedSwords } from "react-icons/gi";

export const getIconComponent = (iconName, color = null) => {
  const iconMap = {
    MessagesSquare,
    CalendarDays,
    UserPlus,
    Handshake,
    Rocket,
    MapPin,
    Building,
    Users,
    Heart,
    Star,
    Trophy,
    Camera,
    Music,
    Coffee,
    ShoppingBag,
    Briefcase,
    GraduationCap,
    MousePointerClick,
    MoreHorizontal,
    AlertTriangle,

    // New icons added below
    Building2,
    UserRound,
    Car,
    Cloud,
    PartyPopper,
    Swords,
    Megaphone,
    AlertCircle,
    Film,
    Laptop,
    FlaskConical,
    Leaf,
    Train,
    Globe,
    BadgeDollarSign,
    Ambulance,
    Clapperboard,
    Shield,
    Shirt,
    BellRing,
    Flag,
    PawPrint,
    Loader2,
    Newspaper,
    TrendingUp,
    HandHeart,
    Sparkles,
    Info,
    RotateCw,
    DollarSign,
    AlertOctagon,
    Speaker,
    Target,
    Vote,
    FaHandcuffs,
    GiCrossedSwords,
    UsersRound,
    Code2,
    LogIn,
    Target,
    Smartphone,
    Sofa,
    Home,
    Package,
    Percent,
    Gift,
    SpeakerIcon,
    Cross,
    ShieldAlert,
    Zap,
    Droplet,
    Refrigerator,
    MessageCircleQuestion,
    Wrench,
    FaToolbox,
    Snowflake,
    Video,
    ArrowUpDown,
    Dumbbell,
    Wifi,
    Trash2
    
  };

  const IconComponent = iconMap[iconName] || MapPin; // fallback
  
  // If color is provided, return the icon with color style
  if (color) {
    const ColoredIconComponent = (props) => <IconComponent {...props} style={{ color }} />;
    ColoredIconComponent.displayName = `Colored${iconName}Icon`;
    return ColoredIconComponent;
  }
  
  return IconComponent;
};    